services:
  gnuhealth-database:
    build: ../../docker-images/postgres-mod/
    env_file:
      - .env
    volumes:
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
      - gnuhealth-data:/var/lib/postgresql/data
      - gnuhealth-pg-socket:/var/run/postgresql
    restart: always
    networks:
      - vhp_network

  gnuhealth:
    build:
      context: ../../docker-images/gnuhealth-radiology/
      args:
        GNUHEALTH_SAO_PORT: ${GNUHEALTH_SAO_PORT}
        GNUHEALTH_WEBDEV_PORT: ${GNUHEALTH_WEBDEV_PORT}
        GNUHEALTH_FHIR_PORT: ${GNUHEALTH_FHIR_PORT}
    env_file:
      - .env
    depends_on:
      - gnuhealth-database
    command: bash /home/gnuhealth/init.sh
    volumes:
      - ./init-gnuhealth.sh:/home/gnuhealth/init.sh
      - gnuhealth-attach:/home/gnuhealth/attach
      # - ./fhir_server.log:/tmp/fhir_server.log
    #networks:
    #  - vhp_network
    network_mode: "service:orthanc"

  orthanc:
    image: weisadre/orthanc-fhir
    command: /run/secrets/
    env_file:
      - .env
    secrets:
      - orthanc.json
    restart: always
    environment:
      - ORTHANC_NAME=${ORTHANC_NAME}
      - ORTHANC_AUTHENTICATION=keycloak
      - KEYCLOAK_REALM=orthanc
      - KEYCLOAK_CLIENT_ID=orthanc
    volumes:
      - orthanc-db:/var/lib/orthanc/db
    networks:
      - vhp_network
    ports:
      - "${ORTHANC_PORT}:8042"
      - "${GNUHEALTH_SAO_PORT}:${GNUHEALTH_SAO_PORT}"
      - "${GNUHEALTH_WEBDEV_PORT}:${GNUHEALTH_WEBDEV_PORT}"
      - "${GNUHEALTH_FHIR_PORT}:${GNUHEALTH_FHIR_PORT}"

secrets:
  orthanc.json:
    file: ./config/orthanc.json

networks:
  vhp_network:
    name: ${VHP_NETWORK_NAME}

volumes:
  gnuhealth-data:
  gnuhealth-pg-socket:
  gnuhealth-attach:
  orthanc-db:
